### ISSUE TITLE
ترفند

### ISSUE THREAD

**Issue by samadii** [hoothassan/dlstar#2]
دور زدن محدودیت ماهانه ۵۵۰ساعته ی سرور رایگان هروکو

ابتدا دو اکانت هروکو بسازید و اپ موردنظرو توی هر دوتا اکانت توسعه بدید
 بعد به کمک این [ربات](t.me/HK_heroku_bot) 
تایم استارت و توقف اتوماتیک اپ‌ها رو جوری زمان‌بندی کنید که روزانه هر کدومشون برای یه نصفه روز فعال باشند

**Comment by hoothassan** [comment]
تشکر ولی دامنه ها متفاوت خواهند بود
